[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fbless"
version = "0.2.1"
description = "Curses based FictionBook2 viewer."
readme = "README"
authors = [
    {name = "Con Radchenko", email = "lankier@gmail.com"}
]
license = "GPL-2.0-only"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Environment :: Console :: Curses",
]
dependencies = [
]

[project.scripts]
fbless = "fbless_lib:main"

[tool.setuptools]
packages = { find = { namespaces = true } }

[tool.setuptools.package-data]
"*" = ["hyph_dicts/*"]


